#N26 Test Properties
n26:
  statistics:
    producer:
      startUpCheckIntervalSeconds: 1
      startUpMaxRetries: 5
      shutdownMaxWaitTimeSeconds: 10
      incrementAmount: 10
      messageDelaySeconds: 0
      outOfOrderThreshold: 10
      outOfOrderMessageDelayAdjustment: 10
      sleepIntervalSeconds: 10
...